### ISSUE TITLE
Conflict with Fabric

### ISSUE THREAD

**Issue by dskatz22** [BranchMetrics/ios-branch-deep-linking#332]
The Branch Pod includes Fabric.h which conflicts with the Fabric framework,  causing the compiler to error on Fabric.with([Crashlytics()]).  Any suggestions on how to resolve

**Comment by ahmednawar** [comment]
@dskatz22 Thanks for bringing this to our attention. I'll look into this and update you with a solution.

**Comment by dskatz22** [comment]
fwiw downgraded to 0.11.18, and is working

**Comment by andiradulescu** [comment]
Happens to me also.

​*Compile Error: definition of 'Fabric' must be imported from module 'Branch.Fabric' before it is required*​
```[Nomad/AppDelegate.m:38:6]
    [Fabric with:@[[Crashlytics class]]];
     ^
I'm not entirely sure, but using @import Fabric; instead of #import <Fabric/Fabric.h> compiled fine.

**Comment by hamdullahshah** [comment]
import the fabric after the branch.
e.g 
`
#import <Branch/Branch.h> 
#import <Fabric/Fabric.h>
`

**Comment by ahmednawar** [comment]
@dskatz22  @andiradulescu I am unable to reproduce this on my end..I created a vanilla project with Pods and Fabric but didn't get any errors. Do you have any steps to reproduce this?

**Comment by andiradulescu** [comment]
@ahmednawar it seems that @hamdullahshah is right. In order to get the error, you need to import the headers like this:

`#import <Fabric/Fabric.h>`
`#import <Branch/Branch.h>`

**Comment by ahmednawar** [comment]
This is very weird..this is the beginning of my AppDelegate and it still compiles and runs..I also changed the order but didn't make any difference 

```
#import "AppDelegate.h"
#import <Fabric/Fabric.h>
#import <Branch/Branch.h>
#import <Crashlytics/Crashlytics.h>

@implementation AppDelegate


- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    // Override point for customization after application launch.
    [Fabric with:@[[Crashlytics class]]];
    [[Branch getInstance] initSessionWithLaunchOptions:launchOptions andRegisterDeepLinkHandler:^(NSDictionary *params, NSError *error) {
        NSLog(@"params %@", params);
    }];

    return YES;
}
```

**Comment by andiradulescu** [comment]
I tried reproducing it again, and it needs to be exactly like this (mind the Crashlytics one):

```
#import <Fabric/Fabric.h>
#import <Crashlytics/Crashlytics.h>
#import <Branch/Branch.h>
```

**Comment by ahmednawar** [comment]
It still compiles for me..if you have the capacity can you try creating a simple project with Fabric and Branch and see if you get the same behavior?

**Comment by dskatz22** [comment]
On my end, I have a Swift project, I'll try to create an empty project to repro this weekend

**Comment by hamdullahshah** [comment]
It's because "Branch" also have a "Fabric.h" file so it get conflicts with that. Check the "Preprocess" file of your app delegate

**Comment by ahmednawar** [comment]
@dskatz22 since you are using Swift, do you use Bridging headers or add `use_frameworks!` to your Podfile?

**Comment by briankracoff** [comment]
We're having the same issue since upgrading to `0.12.0`. We have a swift project and `use_frameworks!` so we're calling `import Fabric` in one file and `import Branch` in a completely separate file.

**Comment by tyten** [comment]
I, too, am running into a similar issue with the inclusion of Fabric in this. Also using `use_frameworks!`

**Comment by ahmednawar** [comment]
@tyten what kind of error are you getting?

**Comment by tyten** [comment]
@ahmednawar I'm hitting a wall with the error `FABKitProtocol.h not found`

Downgrading to 0.11.10 let the app compile. I have Fabric, Branch, and Mopub (which also includes Fabric) in the podfile.

**Comment by derrickstaten** [comment]
@tyten I saw this issue an hour ago. It happened to me because I imported the Branch SDK but not the Fabric folder. An image for reference:
![screen shot 2016-05-12 at 6 40 19 pm](https://cloud.githubusercontent.com/assets/5950251/15235534/0b8befda-1871-11e6-910e-2b7666c948ca.png)

So I removed the SDK. Then I reimported the parent folder `Branch-SDK` which contains the child folders `Branch-SDK` and `Fabric`. It's not the best design, for sure. But after importing it started working.

Can you try that and see whether it works?

**Comment by derrickstaten** [comment]
Are you importing the source files manually, using Cocoapods, or importing the .framework? And are you using Objective C or Swift?

**Comment by tyten** [comment]
@derrickstaten We are using Swift + Cocoapods, latest releases.

**Comment by ahmednawar** [comment]
@dskatz22 @andiradulescu @hamdullahshah @briankracoff @tyten hey guys, since we are unable to reproduce this on our side, having a live debugging session might make sense. If this is a still issue for you, please send us an email to support@branch.io, reference the issue #, and we could schedule a debugging session to fix this. If your project src code is public or you are willing to share code, I am also happy to debug it offline. Getting stuck with a a certain version is not the experience we want you to have using our SDK.

**Comment by vinceis1337** [comment]
Just wanted to add on I'm receiving the same error.
![screen shot 2016-05-18 at 12 10 06 pm](https://cloud.githubusercontent.com/assets/5994871/15368045/8461a3da-1cf1-11e6-9994-d805912cf629.png)

**Comment by ahmednawar** [comment]
@vinceis1337 will you be willing to hop on a call to figure this out?

**Comment by vinceis1337** [comment]
@ahmednawar I'm currently completely revising our project dependencies, but when I complete this process I would definitely be willing to.

**Comment by ahmednawar** [comment]
@vinceis1337 great. Please write to support@branch.io and reference the issue number. We will then schedule a live debugging session and figure it out. If your project src code is public or you are willing to share code, I am also happy to debug it offline.

**Comment by vinceis1337** [comment]
@ahmednawar no need to do a live session, I've identified and fixed the issue in https://github.com/BranchMetrics/ios-branch-deep-linking/pull/360

**Comment by zacwest** [comment]
Still experiencing this with 0.12.2 and including the `mopub-ios-sdk` Cocoapod. It causes the Mopub SDK to error with "FABKitProtocol.h file not found" which doesn't happen with an older version of Branch.

**Comment by ahmednawar** [comment]
@zacwest would you be willing to hop on the phone to figure it out?

**Comment by zacwest** [comment]
Sure, I can hop on the phone. You can email me zac@imgur.com to coordinate.

Alternatively, here's a sample project which cannot compile because of this issue. If you downgrade Branch in the Podfile, it will work without issue.

[BranchHeaderTest.zip](https://github.com/BranchMetrics/ios-branch-deep-linking/files/300985/BranchHeaderTest.zip)

**Comment by ahmednawar** [comment]
@zacwest Awesome! I will test the project and let you know how it goes.

**Comment by ahmednawar** [comment]
@zacwest We worked with the Fabric team and we pushed a new release yesterday that addresses this conflict. Could you please try and let us know if you encounter any issues?

**Comment by zacwest** [comment]
I upgraded the Podfile in the attached project above:

> Installing Branch 0.12.3 (was 0.12.2)
> Installing mopub-ios-sdk 4.7.0 (was 4.6.0)

I still cannot compile:

> …/Pods/mopub-ios-sdk/MoPubSDK/MoPub.m:14:9: 'FABKitProtocol.h' file not found

Are you able to successfully build?

**Comment by ahmednawar** [comment]
@zacwest I couldn't reproduce before but after some digging it turned out I had an old version of Cocoapods and things were working fine. After updating to latest, I could reproduce. We will discuss with the Fabric team and keep you posted. Thanks a lot for your help!

**Comment by ahmednawar** [comment]
@zacwest Quick update: this issue seems to be related exclusively to MoPub at the moment. Integrating with other Fabric kits such as Crashlytics, Answers, and Stripe compiles and runs just fine.

**Comment by aaustin** [comment]
For some extra info, the Fabric team is reaching out internally to the Mopub team to help them fix their headers.

**Comment by leogdion** [comment]
The workaround I found was to add a User Search Path to "FABKitProtocol.h". For instance in my Pods file I set it there:
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['USER_HEADER_SEARCH_PATHS'] = '"${PODS_ROOT}/mopub-ios-sdk/MoPubSDK/Internal/Fabric"'
      config.build_settings['ALWAYS_SEARCH_USER_PATHS'] = 'Yes'
    end
  end
end
```

This of course is a workaround not a fix.

**Comment by marcelosalloum** [comment]
I am having the same issue. Changing the import order didn't fix it.

I noticed the conflict only when I was generating dSYM files (my production build).

**Comment by ahmednawar** [comment]
@marcelosalloum which Fabric kits are you using besides Branch? There is a known issue with integrating MoPub but this is an issue with MoPub itself at the moment. 

Which Branch SDK version are you using?

**Comment by marcelosalloum** [comment]
I only use Fabric, Crashlytics and Answers

**Comment by ahmednawar** [comment]
Are you using the latest Branch SDK?

**Comment by marcelosalloum** [comment]
I was using Branch `v0.12.5` but due to this issue I downgraded to `v0.12.2`.

From `v0.12.3` onwards, it won't work for me and I noticed that `v0.12.3` is the first one to include "Fabric Answers integration", according to [this link](https://cocoapods.org/pods/Branch#changelog).

**Comment by ahmednawar** [comment]
@marcelosalloum Are you using Swift or Objective-C? Also, how did you install Fabric (Pods vs Mac app + XCode)?

**Comment by marcelosalloum** [comment]
Hey @ahmednawar, I am using Objective-C. And I installed Fabric the old way (Mac app)

**Comment by ahmednawar** [comment]
@marcelosalloum I tried a dummy Objective-C project where I integrated Fabric and Crashlytics via the Mac App and added Branch (framework and pod) but didn't get any errors. How did you integrate Branch (Pods, Framework, src code)? If you have a sample project with the error, that would be great as well.

**Comment by marcelosalloum** [comment]
Hey @ahmednawar, I investigated better in my project and found the real cause for this issue (it is my bad for not debugging it correctly). My issue actually was a conflict name with the property `startTime` in the file `BNCServerInterface.m`. As that variable is not contained inside the `@implementation`, It can be seen globally and I was using the same property name in one of my classes.

I am avoiding this issue by renaming my property but I'd like to confirm if there is any particular reason for having the `BNCServerInterface.startTime` outside of the `@implementation`.

**Comment by ahmednawar** [comment]
@marcelosalloum the reason is bad coding on my behalf, my apologies :(. Will fix in our next release. Thanks for letting us know!

**Comment by ahmednawar** [comment]
@marcelosalloum here is the PR https://github.com/BranchMetrics/ios-branch-deep-linking/pull/404

**Comment by tapi** [comment]
I can reproduce this in a test project without any code changes.

It looks as though it can also be fixed with a change to the podspec.
Not sure how much contact you have with mobpub but it probably wouldn't be the worst thing if they made the same change.

**Comment by ahmednawar** [comment]
Thanks @tapi for the PR! Will include in our next release

**Comment by ahmednawar** [comment]
@tapi We've included your PR in our release. Closing here and feel free to re-open if you still encounter issues. Cheers!

**Comment by ninjudd** [comment]
I am still getting this issue with Branch 0.12.9 and mopub-ios-sdk 4.9.0.

For now, this workaround based on leogdion's comment above solves the issue:
```
    post_install do |installer|
      installer.pods_project.targets.each do |target|
        if target.name == 'mopub-ios-sdk' 
          target.build_configurations.each do |config|
            config.build_settings['USER_HEADER_SEARCH_PATHS'] = '"${PODS_ROOT}/mopub-ios-sdk/MoPubSDK/Internal/Fabric"'
            config.build_settings['ALWAYS_SEARCH_USER_PATHS'] = 'Yes'
          end
        end
      end
    end
```

**Comment by tapi** [comment]
We're seeing this with MoPub 4.9.0 as well but were not seeing it with 4.6.0 though `¯\_(ツ)_/¯`

**Comment by ninjudd** [comment]
The strange part is that the 4.9.0 podspec has `private_header_files`, but 4.6.0 does not.

https://github.com/mopub/mopub-ios-sdk/blob/master/mopub-ios-sdk.podspec.json

**Comment by aaustin** [comment]
Sorry about the hassle team.

**Comment by honghaoz** [comment]
Still getting the issue with MoPub 4.9.1. 
This PR https://github.com/mopub/mopub-ios-sdk/pull/168 may fix the issue.

**Comment by honghaoz** [comment]
Here is our post_install workaround for integrating `mopub-ios-sdk (4.9.1)` and `Branch (0.12.11)`
```ruby

post_install do |installer|
	fix_mopub_fabric_header_issue(installer)
end

# Add Fabric headers in USER_HEADER_SEARCH_PATHS and defines ALWAYS_SEARCH_USER_PATHS to YES.
# This is a workaround for integrating `mopub-ios-sdk (4.9.1)` and `Branch (0.12.11)`. Waiting for `mopub-ios-sdk` to fix.
def fix_mopub_fabric_header_issue(installer)
	installer.pods_project.targets.each do |target|
		if target.name == 'mopub-ios-sdk'
			target.build_configurations.each do |config|
				config.build_settings['USER_HEADER_SEARCH_PATHS'] = '"${PODS_ROOT}/mopub-ios-sdk/MoPubSDK/Internal/Fabric"'
				config.build_settings['ALWAYS_SEARCH_USER_PATHS'] = 'Yes'
			end
		end
	end
end
```
